backend:
  name: github
  repo: sudo-vladguru/devlopr-site
  branch: master
  #site_domain: agitated-northcutt-53b578.netlify.app

media_folder: "assets/img/posts" # Media files will be stored in the repo under images/uploads
public_folder: "/assets/img/posts" # The src attribute for uploaded media will begin with /images/uploads
publish_mode: editorial_workflow # To manage status (Edit, Draft, Publish)
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Блог" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Автор", name: "author", widget: "string"}
      - {label: "Название", name: "title", widget: "string"}
      - {label: "Опубликовано", name: "date", widget: "datetime"}
      - {label: "Заглавное изображение", name: "thumbnail-img", widget: "image"}
      - {label: "Категория", name: "category", widget: "string", default: "jekyll"}
      - {label: "Summary", name: "summary", widget: "string"}
      - {label: "Ключевые слова", name: "keywords", widget: "string"}
      - {label: "Тело", name: "body", widget: "markdown"}
      - {label: "Thumbnail", name: "thumbnail", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "string"}
  - name: "page"
    label: "Page"
    folder: "_pages"
    create: true
    slug: ".md"
    fields:
      - {label: "Layout", name: "layout", widget: "select", options: ["about", "blog", "contact", "gallery", "page", "product"]}
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "hidden", default: "//"}
      - {label: "Тело", name: "body", widget: "markdown", required: false}
  - name: "layouts"
    label: "Layouts"
    folder: "_layouts"
    extension: "html"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
      - {label: "Заголовок", name: "title", widget: "string", required: false}
      - {label: "Тело", name: "body", widget: "markdown", required: false}